### ISSUE TITLE
[WICHTIG!!!!] Cannot read property "markers" of undefined

### ISSUE THREAD

**Issue by m4rl0ne** [DerErli/klostermaps-backend#10]
Cannot read property 'markers' of undefined
    at router.post (/Users/marlonarend/Documents/Programming/klostermaps-backend/klostermaps/routes/frontend.js:109:20)

Nachdem ich alles gelöscht habe und komplett neue Karten und Events angelegt habe, geht die Navigation nicht mehr...

**Comment by m4rl0ne** [comment]
Oh, ich weiß woran das liegt. Das ist ein Bug im Pathfinding. Muss ich dir morgen persönlich erklären, das tritt nur unter einem ganz bestimmten Fall auf

**Comment by DerErli** [comment]
Fixed
