### ISSUE TITLE
GET keywords 

### ISSUE THREAD

**Issue by m4rl0ne** [DerErli/klostermaps-backend#8]
Brauch noch ne route, die alle verfügbaren Keywords zurückgibt und zwar in folgender Form:

```
    var content = [
      { title: '205'},
      { title: '311'},
      { title: 'Biologie'},
      { title: 'Aula'},
      { title: 'Innenhof'},
    ];
```
(also natürlich als json result und nicht als variable "content" :D)

**Comment by m4rl0ne** [comment]
Nevermind...

**Comment by m4rl0ne** [comment]
Ups brauch ich doch

**Comment by DerErli** [comment]
Erledigt
